# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='N\xe1zev')),
                ('visible', models.BooleanField(default=True, verbose_name='Zobrazovat')),
                ('sort', models.IntegerField(verbose_name='Po\u0159ad\xed')),
                ('gopay_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='K\xf3d u GoPay dle 12.9 K\xf3dy platebn\xedch metod')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name=b'Poplatek')),
            ],
            options={
                'verbose_name': 'Platebn\xed metoda',
                'verbose_name_plural': 'Platebn\xed metody',
            },
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
