# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 08:41
from __future__ import unicode_literals

from django.db import migrations

def load_payment_methods_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "payment_methods.json")

class Migration(migrations.Migration):

    dependencies = [
        ('gopay', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_payment_methods_from_fixture),
    ]
